# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /opt/unreal-engine

TARGETS = \
	Tower-Android-DebugGame  \
	Tower-Android-Development  \
	Tower-Android-Shipping  \
	Tower-Linux-DebugGame  \
	Tower-Linux-Development  \
	Tower-Linux-Shipping  \
	Tower-LinuxArm64-DebugGame  \
	Tower-LinuxArm64-Development  \
	Tower-LinuxArm64-Shipping  \
	Tower \
	TowerEditor-Linux-DebugGame  \
	TowerEditor-Linux-Development  \
	TowerEditor \
	LiveLinkHub-Linux-DebugGame  \
	LiveLinkHub-Linux-Development  \
	LiveLinkHub \
	DotNetPerforceLib \
	IoStoreOnDemandTests \
	EventLoopUnitTests \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Development  \
	UnrealEditor \
	UnrealGame-Android-DebugGame  \
	UnrealGame-Android-Development  \
	UnrealGame-Android-Shipping  \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Development  \
	UnrealGame-Linux-Shipping  \
	UnrealGame-LinuxArm64-DebugGame  \
	UnrealGame-LinuxArm64-Development  \
	UnrealGame-LinuxArm64-Shipping  \
	UnrealGame\
	configure

BUILD = "$(UNREALROOTPATH)/Engine/Build/BatchFiles/RunUBT.sh"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend TowerEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug TowerEditor-Linux-Debug


Tower-Android-DebugGame:
	 $(BUILD) Tower Android DebugGame  -Project="/home/ernestog/Documents/GameDev/Projects/Unreal Projects/Tower/Tower.uproject" $(ARGS)

Tower-Android-Development:
	 $(BUILD) Tower Android Development  -Project="/home/ernestog/Documents/GameDev/Projects/Unreal Projects/Tower/Tower.uproject" $(ARGS)

Tower-Android-Shipping:
	 $(BUILD) Tower Android Shipping  -Project="/home/ernestog/Documents/GameDev/Projects/Unreal Projects/Tower/Tower.uproject" $(ARGS)

Tower-Linux-DebugGame:
	 $(BUILD) Tower Linux DebugGame  -Project="/home/ernestog/Documents/GameDev/Projects/Unreal Projects/Tower/Tower.uproject" $(ARGS)

Tower-Linux-Development:
	 $(BUILD) Tower Linux Development  -Project="/home/ernestog/Documents/GameDev/Projects/Unreal Projects/Tower/Tower.uproject" $(ARGS)

Tower-Linux-Shipping:
	 $(BUILD) Tower Linux Shipping  -Project="/home/ernestog/Documents/GameDev/Projects/Unreal Projects/Tower/Tower.uproject" $(ARGS)

Tower-LinuxArm64-DebugGame:
	 $(BUILD) Tower LinuxArm64 DebugGame  -Project="/home/ernestog/Documents/GameDev/Projects/Unreal Projects/Tower/Tower.uproject" $(ARGS)

Tower-LinuxArm64-Development:
	 $(BUILD) Tower LinuxArm64 Development  -Project="/home/ernestog/Documents/GameDev/Projects/Unreal Projects/Tower/Tower.uproject" $(ARGS)

Tower-LinuxArm64-Shipping:
	 $(BUILD) Tower LinuxArm64 Shipping  -Project="/home/ernestog/Documents/GameDev/Projects/Unreal Projects/Tower/Tower.uproject" $(ARGS)

Tower: Tower-Linux-Development

TowerEditor-Linux-DebugGame:
	 $(BUILD) TowerEditor Linux DebugGame  -Project="/home/ernestog/Documents/GameDev/Projects/Unreal Projects/Tower/Tower.uproject" $(ARGS)

TowerEditor-Linux-Development:
	 $(BUILD) TowerEditor Linux Development  -Project="/home/ernestog/Documents/GameDev/Projects/Unreal Projects/Tower/Tower.uproject" $(ARGS)

TowerEditor: TowerEditor-Linux-Development

LiveLinkHub-Linux-DebugGame:
	 $(BUILD) LiveLinkHub Linux DebugGame  $(ARGS)

LiveLinkHub-Linux-Development:
	 $(BUILD) LiveLinkHub Linux Development  $(ARGS)

LiveLinkHub: LiveLinkHub-Linux-Development

DotNetPerforceLib: DotNetPerforceLib-Linux-Development

IoStoreOnDemandTests: IoStoreOnDemandTests-Linux-Development

EventLoopUnitTests: EventLoopUnitTests-Linux-Development

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Development:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealEditor: UnrealEditor-Linux-Development

UnrealGame-Android-DebugGame:
	 $(BUILD) UnrealGame Android DebugGame  $(ARGS)

UnrealGame-Android-Development:
	 $(BUILD) UnrealGame Android Development  $(ARGS)

UnrealGame-Android-Shipping:
	 $(BUILD) UnrealGame Android Shipping  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Development:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame-LinuxArm64-DebugGame:
	 $(BUILD) UnrealGame LinuxArm64 DebugGame  $(ARGS)

UnrealGame-LinuxArm64-Development:
	 $(BUILD) UnrealGame LinuxArm64 Development  $(ARGS)

UnrealGame-LinuxArm64-Shipping:
	 $(BUILD) UnrealGame LinuxArm64 Shipping  $(ARGS)

UnrealGame: UnrealGame-Linux-Development

configure:
	$(BUILD) -ProjectFiles -Project="/home/ernestog/Documents/GameDev/Projects/Unreal Projects/Tower/Tower.uproject" -Game 

.PHONY: $(TARGETS)
